### PR TITLE
feat: add substring highlighting

### PR DESCRIPTION
**Pull request by jaschdoc**
Related to https://github.com/flix/highlight.js/issues/7

### CODE REVIEW

**Comment by magnus-madsen** [comment]
What license is this under?

**Comment by jaschdoc** [comment]
Oh, interesting. They are automatically bundled with mdbook.

**Comment by jaschdoc** [comment]
What is mdbook licensed under?

**Comment by magnus-madsen** [comment]
If you check the URLs I think they are MIT. If you just add a comment to each that should be fine.

(note that we are note re-distributing mdbook, we are only using it)

**Comment by jaschdoc** [comment]
Alright, sounds good.

**Comment by jaschdoc** [comment]
Just to be clear, MIT license comment or Apache?

**Comment by magnus-madsen** [comment]
Check the repositories of each file.

**Comment by magnus-madsen** [comment]
And then add something like "Licensed under MIT. See: <link to license>".

**Comment by magnus-madsen** [comment]
By the way, why are these files needed here?

**Comment by magnus-madsen** [comment]
By the way, why are these files needed here?

**Comment by jaschdoc** [comment]
The highlight.js engine parses the code blocks and simply adds html classes to the relevant parts of the DOM. In order to get actual highlighting a style sheet has to add styling via using those selectors. mdBook comes shipped with 3 base themes that are just served to the client. If they are not explicitly overridden in the theme directory of the mdBook project then they are generated. In short, these files are just the generated ones with the extra rule using the `.hljs-subst` selector.

**Comment by magnus-madsen** [comment]
OK, but we still clearly need to state the copyright, license, and origin of each file.

**Pull request merged**
