### PR TITLE
Add documentation for lazy

### PR DESCRIPTION
**Pull request by paulbutcher**

### CODE REVIEW

**Comment by magnus-madsen** [comment]
I have some comments (but they probably require the text to be reworked):

- I would prefer if expensive operation was actually computationally expensive (or something to avoided, e.g. if you were to write your own if-then-else construct).
- I think the example with streams is good, but I would call them that, and then I would show that you can implement e.g. filter, map, and take (see DelayList).

**Comment by magnus-madsen** [comment]
TLDR: I prefer the examples to be "real".

**Comment by magnus-madsen** [comment]
Perhaps reusing parts of `DelayList` would be useful?

**Comment by paulbutcher** [comment]
I'll take a look and see if I can extract something small and simple enough to serve.

**Comment by magnus-madsen** [comment]
Maybe there is some inspiration at: https://v2.ocaml.org/api/Lazy.html

**Comment by magnus-madsen** [comment]
Hmm maybe not really.

**Comment by paulbutcher** [comment]
(I will come back to this, just getting my fork into a more sensible state)

**Pull request closed without merging**
